### ISSUE TITLE
Is an SDL2 warning to be expected?

### ISSUE THREAD

**Issue by RyanParsley** [cardonabits/haxo-rs#12]
I'm just about all set up with my build and running the software for the first time shows the following warning.

fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
fluidsynth: warning: Failed to set thread to high priority

I get that sometimes it's ok to ignore warnings, but don't know enough about the nature of this one to make that call. Is the above warning an issue for me to resolve or should I disregard?

**Comment by jcard0na** [comment]
Hi @RyanParsley ,

The first one is generated by libfluidsynth and seems to be benign.  I don't like it, but have not been able to resolve it.
The second one should disappear when you [run the program as root](https://github.com/cardonabits/haxo-hw/blob/main/docs/development.md#installation-and-launch).
