### ISSUE TITLE
MIDI output via USB

### ISSUE THREAD

**Issue by zigmhount** [cardonabits/haxo-rs#14]
Hey,
Just discovered your project today, and I'm very excited about it!
I could not see in the documentation or in the source code anything about MIDI output - my use case would be to plug the haxophone to a computer and record MIDI into a DAW, and call the fluidsynth soundfont (or any other synth) in there. As far as I understand you do send midi notes to the built-in fluidsynth, so I guess it should be pretty easy to just output this via USB, wouldn't it? Have you already considered or planned that (or is it already implemented)?

**Comment by jcard0na** [comment]
Hi @zigmhount,

Thanks for your encouragement.  A few people have asked about MIDI capabilities, and at the moment this is not implemented.  But as you point out, it should be relatively easy, as we already send midi notes to fluidsyth. [This is the exact line in the code](https://github.com/cardonabits/haxo-rs/blob/main/src/main.rs#L145) where that happens.  

You would need to configure the Raspberry Pi to [act as a USB device](https://cdn-learn.adafruit.com/downloads/pdf/turning-your-raspberry-pi-zero-into-a-usb-gadget.pdf) and then implement a USB midi device class protocol on top of it.  [This library](https://github.com/btrepp/usbd-midi) seems to do the latter, so maybe we could send MIDI to a MIDI host without any hardware modifications, just via the second port on the Raspberry Pi Zero.

At the moment I do not have the bandwidth to try this, but I'll be happy to review any Pull Requests or prototype on my haxophone any code that you might want to try.

Best,

**Comment by zigmhount** [comment]
Thanks for the quick reply!
Unfortunately I know nothing about Rust or this kind of programming, but I'll be happy to try to hack something once I get a bit more time (also not much bandwidth on my side at the moment)! I'll let you know (and I'll probably be asking a ton of questions).
In the meantime, knowing that it is technically feasible, I may just start with backing the project on CrowdSupply and order the hardware :)

**Comment by jcard0na** [comment]
Oh!  I *think* it is feasible, but I cannot be 100% certain until we have prototype it.  I'll see if I can run a simple experiment on my end to try to de-risk it.  I'd hate you get a haxophone and later learn that it would not be useful for you!

**Comment by zigmhount** [comment]
Haha, thanks a lot, but no rush!
For what it's worth, I had trouble with an Arduino-based controller in the past where the chip in my specific board did not support MIDI-USB, so I had to fall back to MIDI over serial, which also works fine as long as something like [ttymidi](https://github.com/cjbarnes18/ttymidi) runs on the connected computer.

**Comment by jcard0na** [comment]
It looks like **I** will be the one asking you questions about MIDI in general then... 😉

**Comment by jcard0na** [comment]
Hi @zigmhount,

Actually the prototyping was easier than expected, and the good news is that I am certain now that it will work without hardware changes, only software.

I was able to load the right kernel drivers on the haxophone to make it appear as a midi device on the host:
```
lsusb | grep Midi
Bus 002 Device 022: ID 17b3:0004 Grey Innovation Linux-USB Midi Gadget
```
On the haxophone, this shows up as a midi device:
```
root@haxophone:/sys/kernel/config/usb_gadget/midi/functions# aplaymidi -l                                         
 Port    Client name                      Port name                                                               
 14:0    Midi Through                     Midi Through Port-0                                                     
 24:0    f_midi                           f_midi     ## <<< That's the one!
 ```

 Which can be used to play midi files that will be received by the host:

```
# on the haxophone
aplaymidi -p 24:0 send_to_host.mid

# on the host
arecord -p XX:X from_haxophone.mid
```

The received file is different, but sounds identical to the file sent.

The last step would be to send the haxophone's MIDI events via this conduit, which probably can be achieved with the right configuration to libsynth, in other words, without changing the code in Rust.

So yes, feeling good about this...

**Comment by zigmhount** [comment]
Hahaha awesome, thanks for investigating this! I'll order right away :)

**Comment by zigmhount** [comment]
Just saw the update on the crowdfunding platform yesterday, looks like
you've made good progress with the MIDI implementation, congrats! :)
Out of curiosity, can the haxophon convert the air flow speed into midi
aftertouch signals for e.g. velocity/volume modulation *after* the attack?
Pitchbend signals according to the pressure on the reed would of course be
awesome, but would probably need a sensor in the mouthpiece itself.

Le sam. 9 sept. 2023 à 19:49, Javier Cardona ***@***.***> a
écrit :

**Comment by zigmhount** [comment]
Nice, thanks!

Le mer. 20 sept. 2023 à 16:26, Javier Cardona ***@***.***> a
écrit :
