### ISSUE TITLE
Startup "pop"

### ISSUE THREAD

**Issue by gerdb** [cardonabits/haxo-rs#17]
Today I tried to understand the startup pop. For this I added delays in the initialization of the synth and you can see, that is pops at the moment, the ALSA driver is started. One solution could be (maybe) to use pulseaudio with the option _module-suspend-on-idle_ so that the ALSA driver is always active. But I would expect at least one pop during booting.

So an other idea was to enable the headphone amplifier after haxo has started. The amplifier has a non-pop feature.
I've disconnected the SD_MODE Pin (4) of the amp from +5V and connected it to GPIO4. An additional 3k3 resistor as pulldown to GND. I wanted to modify the software so that GPIO4 goes HIGH after the haxo startet. But before I could made any modifications I saw ... that it worked as it should. 

I don't no why. But there are no pops anymore. 

:thinking:

**Comment by gerdb** [comment]
Here is how I disconnected the SD pin (pin 4 of U4). My PCB: v1.0.1
![how to disconnect sd](https://www.sebulli.com/haxo/disconnect_SD.png)
First I measured if there is connection between U4 pin 4 and + of capacitor C2 using a thin needle to contact pin 4.
Then I used a sharp knife and cut the copper of the PCB at the marked position.
I checked if the the connection between pin4 and + is lost as it should. Then I removed ab bit of the solder mask by scratching it with the knife and soldered a thin wire.

On the other side of the PCB a soldered a 3k3 resistor between pin 7 and 9 of the rpi connector ( GPIO 4 and GND) and the wire to pin 4.
![rpi connector](https://camo.githubusercontent.com/3d2f358141b7e0daca60615df922792cb2fa965866dca7028d4b508db6409525/68747470733a2f2f7777772e72617370626572727970692d7370792e636f2e756b2f77702d636f6e74656e742f75706c6f6164732f323031322f30362f5261737062657272792d50692d4750494f2d4865616465722d776974682d50686f746f2e706e67)

**Comment by jcard0na** [comment]
Hi @gerdb,

I checked the Linux driver for the MAX98357A:  apparently they do eliminate the pop by delaying the assertion of `SD_MODE` until after the I2C clock is started.  

https://github.com/torvalds/linux/commit/cec5b01f8f1c6064037f3181e7690e3765ed995b

I think I will make the change to the schematic to connect that pin to an unused GPIO.

Cheers,

**Comment by gerdb** [comment]
_"delaying the assertion of SD_MODE until after the I2C clock is started."_
I can confirm this.
I've connected it to GPIO4 and do not set it. But I can see that some other service sets it to HIGH, about 5sec before haxo is started. The GPIO is configured as input during startup. I have an 3k3 pulldown and can see a voltage of some 100mV. This means that there is also some kind of pullup. So I would recommend to also use a pulldown.

so ... it's now more a hardware than a software issue ...

**Comment by gerdb** [comment]
Tested it without pulldown resistor:
There is no audible pop. The resistor is therefore not necessary.
For the first 15sec of boot the voltage at GPIO4 is 2.2V, then for 10s 0V and then for 5s 3.3V until haxo started. (RPI 3B+)

**Comment by jcard0na** [comment]
Thanks for testing this @gerdb!

Apparently changing `/boot/config.txt` as below should configure the max98357a driver to use GPIO4 to control `SD_MODE`

```
 - dtoverlay=max98357a
 + dtoverlay=max98357a,sdmode-pin=4
```

I've made the change to the schematic to connect `SD_MODE` to GPIO4, no pull-ups.  I'm very reassured by reviewing the documentation and your testing that it will work.  Thanks!

Links:

https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/max98357a-overlay.dts
https://forums.raspberrypi.com/viewtopic.php?t=340771

**Comment by jcard0na** [comment]
BTW @gerdb, your contributions have been mentioned in the last crowdfunding project update post: https://www.crowdsupply.com/cardona-bits/haxophone/updates/last-days-of-the-campaign
Thanks for the good work!

**Comment by jcard0na** [comment]
I've manufactured a board that includes this change: https://github.com/cardonabits/haxo-hw/commit/a28321d64bd03642627a374bd779182410e1912a and have confirm that indeed it solves the startup pop.

Thanks for your help in this, @gerdb!
